postgresql: &postgresql
  enabled: true
  host: postgresql
  port: 5432
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  persistence:
    size: 25Gi
  databases:
  - name: "kong"

redis: &redis
  enabled: true
  host: "redis-master"
  port: 6379
  master:
    persistence:
      size: 25Gi

global:
  postgresql: *postgresql
  redis: *redis
  storageClass: "gp2"
  domain: ""
  openai_api_base: ""
  openai_api_version: ""
  openai_type: ""
  openai_api_key: ""
  gpt_model: ""
  bhasini_endpoint_url: ""
  bhasini_api_key: ""
  marqo_url: ""
  environment: ""
  telegram_base_url: ""
  telegram_bot_name: ""
  telegram_bot_token: ""
  token: ""
  botName: ""
  upstream: ""
  random_string: ""
  env: ""
  translation_type: ""
  bucket_type: ""
  
  

# Fill in your public/private keys
nginx-public-ingress: 
  proxy_site_crt: |-
    -----BEGIN CERTIFICATE-----
    
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    
    -----END CERTIFICATE-----

  
  proxy_site_key: |-
    

 
    
